CREATE INDEX CITY_INDEX ON ADDRESS(CITY); /*1-2-3-4*/
CREATE INDEX ON ADDRESS USING GIST("LOCATION"); /*4*/

CREATE INDEX MESSAGE_INDEX_ON_GUEST ON MESSAGE  USING HASH (GUEST_ID); /*5*/
CREATE INDEX MESSAGE_INDEX_ON_HOST ON MESSAGE  USING HASH (HOST_ID);  /*6*/

CREATE INDEX RESIDENCE_HOST_ID ON RESIDENCE USING HASH(HOST_ID);   /*8*/

CREATE INDEX ON RENT USING Btree(GUEST_ID,"RENT_STATUS"); /*9*/
CREATE INDEX ON DAMAGE_REPORT USING HASH(GUEST_ID);       /*9*/


CREATE INDEX RESIDENCE_START_DATE_INDEX ON RENT(START_DATE); /*11*/
CREATE INDEX RESIDENCE_END_DATE_INDEX ON RENT(END_DATE);    /*11*/

