WITH TMP AS (SELECT HOST_ID,PRICE FROM RESIDENCE INNER JOIN RENT ON RESIDENCE_ID = RID WHERE 
			 START_DATE >= '20220101' AND END_DATE < '20230101'
			 AND "RENT_STATUS" = 'Completed'
			
			 UNION ALL
			 
			SELECT HOST_ID,CANCELATION_PENALTY AS PRICE FROM RESIDENCE INNER JOIN RENT ON RESIDENCE_ID = RID WHERE 
			 START_DATE >= '20220101' AND END_DATE < '20230101'
			 AND "RENT_STATUS" = 'Cancelled')
			
			 

SELECT HOST_ID,SUM(PRICE) AS TOTAL_SELL FROM TMP GROUP BY HOST_ID ORDER BY TOTAL_SELL DESC LIMIT 20