SELECT G.national_code,G.personal_information,RR.PEOPLE_COUNT,RR.START_DATE,RR.END_DATE 
FROM RENT_REQUEST AS RR, GUEST AS G,RESIDENCE AS RES
WHERE RR.RID = RES.RESIDENCE_ID AND G.NATIONAL_CODE = RR.GUEST_ID 
AND  RR.REQUEST_STATUS = 'Pending' 
AND RES.HOST_ID='8271448553';
