
WITH RE AS (SELECT RENT.START_DATE AS BEGIN_DATE,RENT.END_DATE AS END_DATE, RENT.RID AS RID,
			RENT.PRICE AS PRICE, DAMAGE_REPORT.PENALTY AS PENALTY, RENT."RENT_STATUS" AS RENT_STATUS,
			RENT.GUEST_ID AS GUEST_ID, RENT.START_DATE AS START_DATE
			 FROM RENT LEFT Join DAMAGE_REPORT ON (RENT.RID = DAMAGE_REPORT.RID AND RENT.GUEST_ID=DAMAGE_REPORT.GUEST_ID AND
														 RENT.START_DATE=DAMAGE_REPORT.START_DATE AND RENT.END_DATE=DAMAGE_REPORT.END_DATE))
SELECT RR.GUEST_ID,A.CITY,RE.PRICE + coalesce(RE.PENALTY,0) AS "TOTAL PRICE", RE.BEGIN_DATE as "START DATE", RE.END_DATE FROM RESIDENCE AS R, RENT_REQUEST AS RR, RE, ADDRESS AS A
WHERE RR.GUEST_ID='8271448553' and RE.RENT_STATUS = 'Completed' AND
(RE.RID = RR.RID AND RE.GUEST_ID = RR.GUEST_ID AND RE.START_DATE = RR.START_DATE AND RE.END_DATE = RR.END_DATE) AND
RR.RID = R.RESIDENCE_ID AND A.RESIDENCE_ID = R.RESIDENCE_ID ORDER BY(RE.BEGIN_DATE) DESC;
